# Generated by Django 5.1.5 on 2025-01-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
